/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alog.view;

import alog.control.Calculator;
import alog.control.Parser;
import alog.control.Scanner;
import alog.model.Expressao;
import alog.model.FuncaoToken;
import alog.model.TipoVariavel;
import alog.model.Token;
import alog.model.Variavel;
import java.util.LinkedList;
import javax.swing.text.DefaultStyledDocument;
import alog.view.append.TextLineNumber;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.Caret;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;

/**
 *
 * @author Caique
 */
public class FrmGui extends javax.swing.JFrame {
    
    StyleContext sc;
    private final Style stylePlain;
    private final int FORMAT_PLAIN = 0;
    
    private final Style stylePerc;
    private final Style styleOper;
    private final int FORMAT_PERC = 1;
    
    private final Style styleError;
    private final int FORMAT_ERROR = 2;
    
    private final Color backgroundDisabled = javax.swing.UIManager.getDefaults().getColor("FormattedTextField.disabledBackground");
    private final Color backgroundEnabled = javax.swing.UIManager.getDefaults().getColor("FormattedTextField.background");
    
    /**
     * Creates new form FrmTeste
     */
    public FrmGui() {
        oldText = "";
        
        sc = new StyleContext();
        
        stylePlain = sc.addStyle("plainBasicao", null);
        stylePlain.addAttribute(StyleConstants.Foreground, Color.BLACK);
        stylePlain.addAttribute(StyleConstants.Background, Color.WHITE);
        
        stylePerc = sc.addStyle("percurso", null);
        stylePerc.addAttribute(StyleConstants.Background, Color.YELLOW);
        
        styleOper = sc.addStyle("percursoOperador", null);
        styleOper.addAttribute(StyleConstants.Background, Color.CYAN);
        
        styleError = sc.addStyle("tokenErrado", null);
        styleError.addAttribute(StyleConstants.Background, Color.RED);
        
        initComponents();
        txpIde.setDocument(new DefaultStyledDocument());
        docIde = (DefaultStyledDocument)txpIde.getDocument();
        docProc = (DefaultStyledDocument)txpProcessamento.getDocument();
        formatacao = FORMAT_PLAIN;
        
        tabVariaveis = (DefaultTableModel)jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txpIde = new javax.swing.JTextPane();
        btnInicioPerc = new javax.swing.JButton();
        btnProxPerc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txpEntrada = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txpSaida = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        txpProcessamento = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEntradaConfirma = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        lblVariavelEntrada = new javax.swing.JLabel();
        btnProcContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interpreter");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(950, 720));

        jScrollPane2.setVerifyInputWhenFocusTarget(false);

        txpIde.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txpIde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txpIdeKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txpIde);

        jScrollPane2.setRowHeaderView(new TextLineNumber(txpIde, 2));

        btnInicioPerc.setText("|< Início");
        btnInicioPerc.setEnabled(false);
        btnInicioPerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioPercActionPerformed(evt);
            }
        });

        btnProxPerc.setText(">> Próximo passo");
        btnProxPerc.setEnabled(false);
        btnProxPerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProxPercActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Nome", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(java.awt.Color.green);
        jTable1.setSelectionForeground(java.awt.Color.black);
        jScrollPane1.setViewportView(jTable1);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txpEntrada.setEditable(false);
        txpEntrada.setBackground(javax.swing.UIManager.getDefaults().getColor("FormattedTextField.disabledBackground"));
        txpEntrada.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txpEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txpEntradaKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(txpEntrada);

        jLabel1.setText("Entrada");

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txpSaida.setEditable(false);
        txpSaida.setBackground(javax.swing.UIManager.getDefaults().getColor("FormattedTextField.disabledBackground"));
        txpSaida.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txpSaida.setMinimumSize(new java.awt.Dimension(13, 66));
        txpSaida.setPreferredSize(new java.awt.Dimension(13, 66));
        jScrollPane6.setViewportView(txpSaida);

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txpProcessamento.setEditable(false);
        txpProcessamento.setBackground(javax.swing.UIManager.getDefaults().getColor("FormattedTextField.disabledBackground"));
        txpProcessamento.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jScrollPane7.setViewportView(txpProcessamento);

        jLabel2.setText("Processamento");

        jLabel3.setText("Saída");

        btnEntradaConfirma.setText("Confirmar");
        btnEntradaConfirma.setEnabled(false);
        btnEntradaConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaConfirmaActionPerformed(evt);
            }
        });

        btnVerificar.setText("Verificar algoritmo");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        lblVariavelEntrada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnProcContinuar.setText("Continuar");
        btnProcContinuar.setEnabled(false);
        btnProcContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                        .addGap(433, 433, 433))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProcContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(317, 317, 317))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVariavelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(btnInicioPerc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProxPerc))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEntradaConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVerificar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnInicioPerc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProxPerc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblVariavelEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEntradaConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProcContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnInicioPercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioPercActionPerformed
        if (tokenAnt != null){
            docIde.setCharacterAttributes(tokenAnt.getPosicao(), tokenAnt.getTamanho(), stylePlain, true);
            tokenAnt = null;
        }
        
        Scanner scanner = new Scanner(oldText);
        Parser parser = new Parser(scanner.getAll());
        expressoes = new LinkedList<>();
        int erros = 0;
        
        while (parser.hasNext()){
            Expressao e = parser.parseExpression();
            switch (e.getTipo()){
                case CRIACAO_VARIAVEL:
                case ENTRADA_DE_DADOS:
                case SAIDA_DE_DADOS:
                    e.setIndice(1);
                    break;
                default:
                    break;
            }
            expressoes.add(e);
        }
        
        System.err.println(parser.getStringErros());
        if (parser.balanceamentoBlocos() != 0){
            int bl = parser.balanceamentoBlocos();
            System.err.println("Blocos INÍCIO-FIM desbalanceados - " + 
                    (bl > 0 ? "Necessário fechamento de " + bl + " INÍCIO" : (-bl) + " fechamentos FIM desnecessários"));
            erros ++;
        }
        
        if (erros + parser.getNumErros() > 0){
            JOptionPane.showMessageDialog(this, erros + " erros encontrados - verifique seu algoritmo", "Verificação concluída", JOptionPane.WARNING_MESSAGE);
            formatacao = FORMAT_ERROR;
            for (Token t : parser.getTokensErros()){
                docIde.setCharacterAttributes(t.getPosicao(), t.getTamanho(), styleError, true);
            }
            
            btnProxPerc.setEnabled(false);
            btnInicioPerc.setEnabled(false);
        } else {
            exprIndex = 1;
            operacaoCondicional = false;
            nomeVar = "";
            
            variaveis = new HashMap<>();
            varOrdem = new HashMap<>();
            expressao = expressoes.getFirst();
            tabVariaveis.setRowCount(0);
            
            txpEntrada.setText("");
            txpEntrada.setEditable(false);
            txpEntrada.setBackground(backgroundDisabled);

            docProc.setCharacterAttributes(0, docProc.getLength(), stylePlain, true);
            txpProcessamento.setText("");
            txpProcessamento.setBackground(backgroundDisabled);

            txpSaida.setText("");
            txpSaida.setBackground(backgroundDisabled);
        
            btnVerificar.setEnabled(false);
            btnProxPerc.setEnabled(true);
            btnInicioPerc.setEnabled(false);
        }
    }//GEN-LAST:event_btnInicioPercActionPerformed
    
    private void btnProxPercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxPercActionPerformed
        btnInicioPerc.setEnabled(true);
        
        if (tokenAnt != null){
            docIde.setCharacterAttributes(tokenAnt.getPosicao(), tokenAnt.getTamanho(), stylePlain, true);
        }
        
        docProc.setCharacterAttributes(0, docProc.getLength(), stylePlain, true);
        txpEntrada.setText("");
        
        txpProcessamento.setText("");
        txpProcessamento.setBackground(backgroundDisabled);
        
        if (!expressao.hasNextToken()){
            if (!execProx){
                execProx = true;
                exprIndex++;
            }
            if (exprIndex < expressoes.size()){
                expressao = expressoes.get(exprIndex++);
            } else {
                btnProxPerc.setEnabled(false);
                formatacao = FORMAT_PLAIN;
                JOptionPane.showMessageDialog(this, "Execução concluída", "Execução concluída", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
        }
        
        btnProxPerc.setEnabled(expressao.hasNextToken() || exprIndex < expressoes.size());
        
        formatacao = FORMAT_PERC;
        Token token = expressao.getNextToken();
        docIde.setCharacterAttributes(token.getPosicao(), token.getTamanho(), stylePerc, true);
        jTable1.clearSelection();
        
        switch(expressao.getTipo()){
            case DELIM_BLOCO:
                switch (token.getFuncaoToken()){
                    case RES_BLOCO_INICIO:
                        bloco ++;
                        break;
                    case RES_BLOCO_FIM:
                        bloco --;
                        break;
                }
                break;
            case CRIACAO_VARIAVEL:
                TipoVariavel tipoVar;
                switch (expressao.getTokenAt(0).getFuncaoToken()){
                    case IDENT_TIPO_INTEIRO:
                        tipoVar = TipoVariavel.INTEIRO;
                        break;
                    case IDENT_TIPO_REAL:
                        tipoVar = TipoVariavel.REAL;
                        break;
                    case IDENT_TIPO_CARACTER:
                    default:
                        tipoVar = TipoVariavel.CARACTER;
                        break;
                }
                nomeVar = token.getPalavra();
                Variavel variavel = new Variavel(tipoVar, nomeVar);
                variaveis.put(nomeVar, variavel);

                ArrayList<Variavel> lista = new ArrayList(variaveis.values());
                Collections.sort(lista, (v1, v2) -> {
                    int comp = v1.getTipo().toString().compareTo(v2.getTipo().toString());
                    if (comp == 0){
                        return v1.getNome().compareToIgnoreCase(v2.getNome());
                    } else {
                        return comp;
                    }
                });
                
                tabVariaveis.setRowCount(0);
                for (Variavel v : lista){
                    tabVariaveis.addRow(new String[]{v.getTipo().toString(),v.getNome(),v.getValor()});
                    varOrdem.put(v.getNome(), lista.indexOf(v));
                }
                
                jTable1.addRowSelectionInterval(varOrdem.get(nomeVar), varOrdem.get(nomeVar));
                break;
            case ENTRADA_DE_DADOS:
                jTable1.clearSelection();
                
                nomeVar = token.getPalavra();
                execEntradaDados();
                break;
                
            case SAIDA_DE_DADOS:
                txpSaida.setBackground(backgroundEnabled);
                
                String textoSaida = "";
                switch (token.getFuncaoToken()){
                    case CONST_CARACTER:
                        textoSaida = token.getPalavra().replace("\"", "");
                        break;
                    case CONST_INTEIRA:
                    case CONST_REAL:
                        textoSaida = token.getPalavra();
                        break;
                    case IDENT_NOME_VARIAVEL:
                        nomeVar = token.getPalavra();
                        variavel = variaveis.get(nomeVar);
                        
                        if (variavel == null){
                            System.err.println("Variável " + nomeVar + " não encontrada");
                        } else {
                            jTable1.addRowSelectionInterval(varOrdem.get(nomeVar), varOrdem.get(nomeVar));
                            switch (variavel.getTipo()){
                                case REAL:
                                    int indicePonto = variavel.getValor().indexOf(".");
                                    if (indicePonto >= 0 && variavel.getValor().substring(indicePonto + 1).length() > 3){
                                        textoSaida = variavel.getValor().substring(0, indicePonto + 4);
                                        break;
                                    }
                                case INTEIRO:
                                case CARACTER:
                                    textoSaida = variavel.getValor();
                                    break;
                            }
                        }
                        break;
                }
                if (!expressao.hasNextToken()){
                    textoSaida += "\n";
                }
                txpSaida.setText(txpSaida.getText() + textoSaida);
                break;
                
            case OPERACAO_ATRIBUICAO:
            case OPERACAO_ARITMETICA:
                Token ultimoExpr = expressao.getTokenAt(expressao.getNumTokens() - 1);
                Token newToken = new Token();
                int posInicio = token.getPosicao();
                int offset = (ultimoExpr.getPosicao() + ultimoExpr.getTamanho()) - posInicio;
                docIde.setCharacterAttributes(posInicio, offset, stylePerc, true);
                
                newToken.setLinha(token.getLinha());
                newToken.setColuna(token.getColuna());
                newToken.setPosicao(token.getPosicao());
                newToken.setOrdem(token.getOrdem());
                try {
                    newToken.atualizaPalavra(docIde.getText(posInicio, offset));
                } catch (BadLocationException ex){
                    System.err.println(ex.toString());
                }
                token = newToken;
                
                expressao.setIndice(0);
                operacaoCondicional = false;
                execOperacao();
                
                break;
                
            case OPERACAO_LOGICA:
                switch (token.getFuncaoToken()){
                    case RES_COND_SE:
                        //docIde.setCharacterAttributes(token.getPosicao(), token.getTamanho(), stylePlain, true);
                        ultimoExpr = expressao.getTokenAt(expressao.getNumTokens() - 1);
                        newToken = new Token();
                        posInicio = token.getPosicao();
                        offset = (ultimoExpr.getPosicao() + ultimoExpr.getTamanho()) - posInicio;
                        docIde.setCharacterAttributes(posInicio, offset, stylePerc, true);

                        newToken.setLinha(token.getLinha());
                        newToken.setColuna(token.getColuna());
                        newToken.setPosicao(token.getPosicao());
                        newToken.setOrdem(token.getOrdem());
                        try {
                            newToken.atualizaPalavra(docIde.getText(posInicio, offset));
                        } catch (BadLocationException ex){
                            System.err.println(ex.toString());
                        }
                        token = newToken;

                        expressao.setIndice(1);
                        operacaoCondicional = true;
                        execOperacao();

                        break;
                    case RES_COND_SENAO:
                        execProx = !condResult;
                        break;
                }
                break;
                
            case _INVALIDO:
                System.err.println("Expressão inválida");
                System.err.println("\t" + expressao.getTexto());
                
                formatacao = FORMAT_ERROR;
                docIde.setCharacterAttributes(token.getPosicao(), token.getTamanho(), styleError, true);
                
                break;
            default:
                System.err.println("Expressão indefinida");
                System.err.println("\t" + expressao.getTexto());
                
                formatacao = FORMAT_ERROR;
                docIde.setCharacterAttributes(token.getPosicao(), token.getTamanho(), styleError, true);
                
                break;
        }
        
        tokenAnt = token;
        
        if (!execProx && token.getFuncaoToken() == FuncaoToken.RES_COND_SENAO){
            btnProxPercActionPerformed(evt);
        }
    }//GEN-LAST:event_btnProxPercActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        if (tokenAnt != null){
            docIde.setCharacterAttributes(tokenAnt.getPosicao(), tokenAnt.getTamanho(), stylePlain, true);
            tokenAnt = null;
        }
        
        oldText = txpIde.getText();
        
        if (oldText.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nada para verificar - algoritmo vazio", "Verificação concluída", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Scanner scanner = new Scanner(oldText);
        Parser parser = new Parser(scanner.getAll());
        expressoes = new LinkedList<>();
        int erros = 0;
        
        while (parser.hasNext()){
            Expressao e = parser.parseExpression();
            switch (e.getTipo()){
                case CRIACAO_VARIAVEL:
                case ENTRADA_DE_DADOS:
                case SAIDA_DE_DADOS:
                    e.setIndice(1);
                    break;
                default:
                    break;
            }
            expressoes.add(e);
        }
        
        System.err.println(parser.getStringErros());
        if (parser.balanceamentoBlocos() != 0){
            int bl = parser.balanceamentoBlocos();
            System.err.println("Blocos INÍCIO-FIM desbalanceados - " + 
                    (bl > 0 ? "Necessário fechamento de " + bl + " INÍCIO" : (-bl) + " fechamentos FIM desnecessários"));
            erros ++;
        }
        
        if ((erros = erros + parser.getNumErros()) > 0){
            JOptionPane.showMessageDialog(this, erros + " erros encontrados - verifique seu algoritmo", "Verificação concluída", JOptionPane.WARNING_MESSAGE);
            formatacao = FORMAT_ERROR;
            for (Token t : parser.getTokensErros()){
                docIde.setCharacterAttributes(t.getPosicao(), t.getTamanho(), styleError, true);
            }
            btnProxPerc.setEnabled(false);
            btnInicioPerc.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum erro encontrado - pronto para execução", "Verificação concluída", JOptionPane.INFORMATION_MESSAGE);
            
            exprIndex = 1;
            operacaoCondicional = false;
            nomeVar = "";
            
            variaveis = new HashMap<>();
            varOrdem = new HashMap<>();
            expressao = expressoes.getFirst();
            tabVariaveis.setRowCount(0);
            
            txpEntrada.setText("");
            txpEntrada.setEditable(false);
            txpEntrada.setBackground(backgroundDisabled);

            docProc.setCharacterAttributes(0, docProc.getLength(), stylePlain, true);
            txpProcessamento.setText("");
            txpProcessamento.setBackground(backgroundDisabled);

            txpSaida.setText("");
            txpSaida.setBackground(backgroundDisabled);
        
            btnVerificar.setEnabled(false);
            btnProxPerc.setEnabled(true);
            btnInicioPerc.setEnabled(false);
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void txpIdeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txpIdeKeyReleased
        String text = txpIde.getText();
        if (!text.equals(oldText)){
            btnVerificar.setEnabled(true);
        }
        if (formatacao != FORMAT_PLAIN){
            docIde.setCharacterAttributes(0, docIde.getLength(), stylePlain, true);
        }
        switch (evt.getKeyCode()){
            case KeyEvent.VK_TAB:
            default:
                break;
        }
    }//GEN-LAST:event_txpIdeKeyReleased

    private void execEntradaDados(){
        Variavel variavel = variaveis.get(nomeVar);
        if (variavel == null){
            JOptionPane.showMessageDialog(this, "Variável " + nomeVar + " não encontrada", "Erro de execução", JOptionPane.ERROR_MESSAGE);
        } else {
            jTable1.clearSelection();
            jTable1.setSelectionBackground(Color.YELLOW);
            jTable1.addRowSelectionInterval(varOrdem.get(nomeVar), varOrdem.get(nomeVar));
            
            lblVariavelEntrada.setText("Variável " + nomeVar + " (tipo " + variavel.getTipo() + "):");
            btnProxPerc.setEnabled(false);
            
            txpEntrada.setBackground(backgroundEnabled);
            txpEntrada.setEditable(true);
            txpEntrada.setText("");
            btnEntradaConfirma.setEnabled(true);
            txpEntrada.requestFocus();
            Caret caret = txpEntrada.getCaret();
            caret.setDot(0);
            txpEntrada.setCaret(caret);
        }
    }
    
    private void btnEntradaConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaConfirmaActionPerformed
        Variavel variavel = variaveis.get(nomeVar);
        
        boolean valorValido = true;
        String linha = txpEntrada.getText().replace("\n", "");

        switch(variavel.getTipo()){
            case CARACTER:
                variavel.setValor(linha);
                break;
            case INTEIRO:
                try {
                    int valor = Integer.parseInt(linha);
                    variavel.setValor(String.valueOf(valor));
                } catch (NumberFormatException ex){
                    JOptionPane.showMessageDialog(this, "Valor \"" + linha + "\" inválido - esperado valor inteiro", "Valor inválido", JOptionPane.WARNING_MESSAGE);
                    valorValido = false;
                }
                break;
            case REAL:
                try {
                    double valor = Double.parseDouble(linha);
                    variavel.setValor(String.valueOf(valor));
                } catch (NumberFormatException ex){
                    JOptionPane.showMessageDialog(this, "Valor \"" + linha + "\" inválido - esperado valor real", "Valor inválido", JOptionPane.WARNING_MESSAGE);
                    valorValido = false;
                }
                break;
        }
        
        if (valorValido){
            variaveis.put(nomeVar, variavel);
            jTable1.setSelectionBackground(Color.GREEN);
            tabVariaveis.setValueAt(variavel.getValor(), varOrdem.get(nomeVar), 2);
            
            jTable1.clearSelection();
            jTable1.addRowSelectionInterval(varOrdem.get(nomeVar), varOrdem.get(nomeVar));

            boolean proxHabilita = expressao.hasNextToken() || exprIndex < expressoes.size();
            btnProxPerc.setEnabled(proxHabilita);
            
            lblVariavelEntrada.setText("");
            btnEntradaConfirma.setEnabled(false);
            txpEntrada.setText("");
            txpEntrada.setEditable(false);
            txpEntrada.setBackground(backgroundDisabled);
            btnProxPerc.requestFocus();
            if (expressao.hasNextToken()){
                btnProxPercActionPerformed(evt);
            }
        } 
    }//GEN-LAST:event_btnEntradaConfirmaActionPerformed

    private void txpEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txpEntradaKeyPressed
        evt.consume();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnEntradaConfirmaActionPerformed(null);
        }
    }//GEN-LAST:event_txpEntradaKeyPressed

    private LinkedList<Token> pilha;
    private LinkedList<Token> saida;
    
    private void execOperacao(){
        btnProxPerc.setEnabled(false);
        int funcParam = 0;
        int contParam = 0;
        
        pilha = new LinkedList<>();
        saida = new LinkedList<>();
        
        String exibicao = "";
        int col = 0;
        int ordem = 0;
        
        while (expressao.hasNextToken()){
            Token token = expressao.getNextToken();
            
            token.setLinha(0);
            token.setColuna(col);
            token.setPosicao(col);
            token.setOrdem(ordem++);
            
            if (exibicao.isEmpty()){
                exibicao = token.getPalavra();
            } else {
                exibicao += " " + token.getPalavra();
            }
            col += token.getTamanho() + 1;
            
            switch (token.getFuncaoToken()){
                case IDENT_NOME_VARIAVEL:
                case CONST_CARACTER:
                case CONST_INTEIRA:
                case CONST_REAL:
                    saida.add(token);
                    if (funcParam > 0){
                        contParam++;
                    }
                    if (contParam > funcParam){
                        System.err.println("Chamada de função inválida (muitos argumentos) - esperava " + funcParam + " argumentos, encontrou " + contParam);
                    }
                    break;

                case OP_ATRIBUICAO:
                case OP_SOMA:
                case OP_SUBTRACAO:
                case OP_MULTIPLICACAO:
                case OP_DIV_INTEIRA:
                case OP_DIV_REAL:
                case OP_MOD:
                case OP_MAIOR:
                case OP_MAIOR_IGUAL:
                case OP_MENOR:
                case OP_MENOR_IGUAL:
                case OP_IGUAL:
                case OP_DIFERENTE:
                case OP_E:
                case OP_OU:
                    while (!pilha.isEmpty() && pilha.peek().getPrecedencia() > token.getPrecedencia()){
                        saida.add(pilha.pop());
                    }
                    pilha.push(token);
                    break;
                
                case LIB_MATH_POT:
                    while (!pilha.isEmpty() && pilha.peek().getPrecedencia() > token.getPrecedencia()){
                        saida.add(pilha.pop());
                    }
                    pilha.push(token);
                    contParam = 0;
                    funcParam = 2;
                    break;
                    
                case LIB_MATH_RAIZ:
                    while (!pilha.isEmpty() && pilha.peek().getPrecedencia() > token.getPrecedencia()){
                        saida.add(pilha.pop());
                    }
                    pilha.push(token);
                    contParam = 0;
                    funcParam = 1;
                    break;
                    
                case DELIM_PARENTESES_ABRE:
                    pilha.push(token);
                    break;
                    
                case DELIM_PARENTESES_FECHA:
                    if (contParam < funcParam){
                        System.err.println("Chamada de função inválida (poucos argumentos) - esperava " + funcParam + " argumentos, encontrou " + contParam);
                    } else {
                        funcParam = 0;
                        contParam = 0;
                    }
                    while (!pilha.isEmpty()){
                        Token out = pilha.pop();
                        if (out.getFuncaoToken() == FuncaoToken.DELIM_PARENTESES_ABRE){
                            break;
                        } else {
                            saida.add(out);
                        }
                    }
                    break;
                    
                case RES_COND_ENTAO:
                    break;
            }
        }
        while (!pilha.isEmpty()){
            saida.add(pilha.pop());
        }
        
        txpProcessamento.setBackground(backgroundEnabled);
        btnProcContinuar.setEnabled(true);
        txpProcessamento.setText(exibicao);
    }
    
    public Variavel retornaVariavel(Token token){
        Variavel temp;
        String nomeVar = "temp" + token.getOrdem();
        switch (token.getFuncaoToken()){
            case IDENT_NOME_VARIAVEL:
                temp = variaveis.get(token.getPalavra());
                jTable1.addRowSelectionInterval(varOrdem.get(token.getPalavra()), varOrdem.get(token.getPalavra()));
                break;
            case CONST_CARACTER:
                temp = new Variavel(TipoVariavel.CARACTER, nomeVar);
                temp.setValor(token.getPalavra().replace("\"", ""));
                break;
            case CONST_INTEIRA:
                temp = new Variavel(TipoVariavel.INTEIRO, nomeVar);
                temp.setValor(token.getPalavra());
                break;
            case CONST_REAL:
                temp = new Variavel(TipoVariavel.REAL, nomeVar);
                temp.setValor(token.getPalavra());
                break;
            default:
                System.out.println("Tipo de token inválido para efetuar operação: " + token.getFuncaoToken());
                temp = null;
        }
        return temp;
    }
    
    private void btnProcContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcContinuarActionPerformed
        Calculator calculadora;
        boolean popTokens = true;
        jTable1.clearSelection();
        
        while (!saida.isEmpty() && popTokens){
            Token token = saida.pop();
            Token resultToken;
            Variavel op1, op2;
            switch (token.getFuncaoToken()){
                case IDENT_NOME_VARIAVEL:
                case CONST_CARACTER:
                case CONST_INTEIRA:
                case CONST_REAL:
                    pilha.push(token);
                    break;
                case OP_SOMA:
                case OP_SUBTRACAO:
                case OP_MULTIPLICACAO:
                case OP_DIV_INTEIRA:
                case OP_DIV_REAL:
                case OP_MOD:
                    docProc.setCharacterAttributes(0, docProc.getLength(), stylePlain, true);
                    imprimeTokens(token);
                    
                    Token tok2 = pilha.pop();
                    Token tok1 = pilha.pop();
                    op2 = retornaVariavel(tok2);
                    op1 = retornaVariavel(tok1);
                    
                    docProc.setCharacterAttributes(tok1.getPosicao(), tok1.getTamanho(), stylePerc, true);
                    docProc.setCharacterAttributes(token.getPosicao(), token.getTamanho(), styleOper, true);
                    docProc.setCharacterAttributes(tok2.getPosicao(), tok2.getTamanho(), stylePerc, true);
                    
                    token.setColuna(tok1.getColuna());
                    
                    calculadora = new Calculator(token);
                    resultToken = calculadora.executaOperacaoAritmetica(op1, op2);
                    
                    if (resultToken == null){
                        System.err.println("Operação não executada");
                        popTokens = false;
                    } else {
                        pilha.push(resultToken);
                        popTokens = false;
                    }
                    break;
                    
                case OP_MAIOR:
                case OP_MAIOR_IGUAL:
                case OP_MENOR:
                case OP_MENOR_IGUAL:
                case OP_IGUAL:
                case OP_DIFERENTE:
                    docProc.setCharacterAttributes(0, docProc.getLength(), stylePlain, true);
                    imprimeTokens(token);
                    
                    tok2 = pilha.pop();
                    tok1 = pilha.pop();
                    op2 = retornaVariavel(tok2);
                    op1 = retornaVariavel(tok1);
                    
                    docProc.setCharacterAttributes(tok1.getPosicao(), tok1.getTamanho(), stylePerc, true);
                    docProc.setCharacterAttributes(token.getPosicao(), token.getTamanho(), styleOper, true);
                    docProc.setCharacterAttributes(tok2.getPosicao(), tok2.getTamanho(), stylePerc, true);
                    
                    token.setColuna(tok1.getColuna());
                    
                    calculadora = new Calculator(token);
                    resultToken = calculadora.executaOperacaoRelacional(op1, op2);
                    
                    if (resultToken == null){
                        System.err.println("Operação não executada");
                        popTokens = false;
                    } else {
                        pilha.push(resultToken);
                        popTokens = false;
                    }
                    break;
                    
                case OP_E:
                case OP_OU:
                    docProc.setCharacterAttributes(0, docProc.getLength(), stylePlain, true);
                    imprimeTokens(token);
                    
                    tok2 = pilha.pop();
                    tok1 = pilha.pop();
                    op2 = retornaVariavel(tok2);
                    op1 = retornaVariavel(tok1);
                    
                    docProc.setCharacterAttributes(tok1.getPosicao(), tok1.getTamanho(), stylePerc, true);
                    docProc.setCharacterAttributes(token.getPosicao(), token.getTamanho(), styleOper, true);
                    docProc.setCharacterAttributes(tok2.getPosicao(), tok2.getTamanho(), stylePerc, true);
                    
                    token.setColuna(tok1.getColuna());
                    
                    calculadora = new Calculator(token);
                    resultToken = calculadora.executaOperacaoLogica(op1, op2);
                    
                    if (resultToken == null){
                        System.err.println("Operação não executada");
                        popTokens = false;
                    } else {
                        pilha.push(resultToken);
                        popTokens = false;
                    }
                    break;
                    
                case LIB_MATH_POT:
                    op2 = retornaVariavel(pilha.pop());
                    op1 = retornaVariavel(pilha.pop());
                    calculadora = new Calculator(token);
                    resultToken = calculadora.executaFuncaoPot(op1, op2);
                    if (resultToken == null){
                        System.err.println("Operação não executada");
                        popTokens = false;
                    } else {
                        pilha.push(resultToken);
                        popTokens = false;
                    }
                    break;
                    
                case LIB_MATH_RAIZ:
                    op1 = retornaVariavel(pilha.pop());
                    calculadora = new Calculator(token);
                    resultToken = calculadora.executaFuncaoRaiz(op1);
                    if (resultToken == null){
                        System.err.println("Operação não executada");
                        popTokens = false;
                    } else {
                        pilha.push(resultToken);
                        popTokens = false;
                    }
                    break;
                    
                case OP_ATRIBUICAO:
                    docProc.setCharacterAttributes(0, docProc.getLength(), stylePlain, true);
                    imprimeTokens(token);
                    
                    Token tokValor = pilha.pop();
                    op1 = retornaVariavel(tokValor);
                    Token tokVar = pilha.pop();
                    
                    docProc.setCharacterAttributes(tokValor.getPosicao(), tokValor.getTamanho(), stylePerc, true);
                    docProc.setCharacterAttributes(token.getPosicao(), token.getTamanho(), styleOper, true);
                    docProc.setCharacterAttributes(tokVar.getPosicao(), tokVar.getTamanho(), stylePerc, true);
                    
                    if (tokVar.getFuncaoToken() != FuncaoToken.IDENT_NOME_VARIAVEL){
                        System.err.println("Atribuição inválida - Esperava Variável, encontrou Constante");
                    }
                    docProc.setCharacterAttributes(0, docProc.getLength(), stylePlain, true);
                    
                    nomeVar = tokVar.getPalavra();
                    Variavel variavel = variaveis.get(nomeVar);
                    if (variavel == null){
                        JOptionPane.showMessageDialog(this, "Variável " + nomeVar + " não encontrada", "Erro de execução", JOptionPane.ERROR_MESSAGE);
                    } else {
                        switch (variavel.getTipo()){
                            case INTEIRO:
                                if (op1.getTipo() != TipoVariavel.INTEIRO){
                                    System.err.println("Atribuição inválida - Esperava " + variavel.getTipo() + ", encontrou " + op1.getTipo());
                                    break;
                                }
                                variavel.setValor(op1.getValor());
                                break;
                            case REAL:
                                if (op1.getTipo() != TipoVariavel.REAL && op1.getTipo() != TipoVariavel.INTEIRO){
                                    System.err.println("Atribuição inválida - Esperava " + variavel.getTipo() + ", encontrou " + op1.getTipo());
                                }
                                variavel.setValor(op1.getValor());
                                break;
                            case CARACTER:
                                if (op1.getTipo() != TipoVariavel.CARACTER){
                                    System.err.println("Atribuição inválida - Esperava " + variavel.getTipo() + ", encontrou " + op1.getTipo());
                                }
                                variavel.setValor(op1.getValor());
                                break;
                        }
                        variaveis.put(nomeVar, variavel);
                        tabVariaveis.setValueAt(variavel.getValor(), varOrdem.get(nomeVar), 2);
                        jTable1.addRowSelectionInterval(varOrdem.get(nomeVar), varOrdem.get(nomeVar));
                        
                        popTokens = false;
                    }
            }
        }
        
        if (saida.isEmpty()){
            if (pilha.size() == 1 && operacaoCondicional){
                Token t = pilha.peek();
                Variavel r = retornaVariavel(t);
                if (r == null || r.getTipo() != TipoVariavel.INTEIRO){
                    System.err.println("Erro na execução - variável para token " + t + " inválida");
                } else {
                    condResult = r.getValorInteiro() == 1;
                    docProc.setCharacterAttributes(0, docProc.getLength(), stylePlain, true);
                    execProx = condResult;
                    operacaoCondicional = false;
                }
            } else {
                if (pilha.size() == 1){
                    operacaoCondicional = true;
                    imprimeTokens(pilha.pop());
                }
                btnProcContinuar.setEnabled(false);
                btnProxPerc.setEnabled(expressao.hasNextToken() || exprIndex < expressoes.size());
                pilha = new LinkedList<>();
                saida = new LinkedList<>();
            }
        }
    }//GEN-LAST:event_btnProcContinuarActionPerformed
    
    private void imprimeTokens(Token op){
        LinkedList<Token> tokens = new LinkedList<>();
        tokens.addAll(pilha);
        tokens.addAll(saida);
        tokens.add(op);
        Collections.sort(tokens, (tk1, tk2) -> {
            return Integer.compare(tk1.getOrdem(), tk2.getOrdem());
        });
        
        String exibicao = "";
        
        for (Token t : tokens){
            String palavra;
            if (t.getPalavra().equals(op.getPalavra()) && operacaoCondicional){
                palavra = t.getPalavra().equals("0") ? "Falso" :  t.getPalavra().equals("1") ? "Verdadeiro" : t.getPalavra();
            } else {
                palavra = t.getPalavra();
            }
            exibicao += (exibicao.isEmpty() ? "" : " ") + palavra;
        }
        txpProcessamento.setText(exibicao);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmGui().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntradaConfirma;
    private javax.swing.JButton btnInicioPerc;
    private javax.swing.JButton btnProcContinuar;
    private javax.swing.JButton btnProxPerc;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblVariavelEntrada;
    private javax.swing.JTextPane txpEntrada;
    private javax.swing.JTextPane txpIde;
    private javax.swing.JTextPane txpProcessamento;
    private javax.swing.JTextPane txpSaida;
    // End of variables declaration//GEN-END:variables
    private LinkedList<Expressao> expressoes;
    private HashMap<String,Variavel> variaveis;
    private HashMap<String,Integer> varOrdem;
    private Expressao expressao;
    private int exprIndex;
    private int tabIndex;
    private DefaultStyledDocument docIde;
    private DefaultStyledDocument docProc;
    private int formatacao;
    private String oldText;
    
    private DefaultTableModel tabVariaveis;
    
    private int bloco = 0;
    private boolean operacaoCondicional = false;
    private boolean condResult = false;
    private boolean execProx = true;
    
    private Token tokenAnt = null;
    private String nomeVar;
}
