/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.alg.gui;

import fatec.alg.geral.log.Erro;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alani
 */
public class FrmListaErros extends javax.swing.JFrame {

    /**
     * Creates new form FrmListaErros
     */
    public FrmListaErros() {
        initComponents();
        
    }
    
    public void setListaErros(List<Erro> listaErros) {
        tabErros = (DefaultTableModel)tblErros.getModel();
        
        tabErros.setRowCount(0);
        for (Erro erro : listaErros){
            tabErros.addRow(new String[]{
                erro.getTipo().toString(),
                String.valueOf(erro.getToken().getLinha()+1),
                String.valueOf(erro.getToken().getColuna()+1),
                erro.getMensagem()
            });
        }
        
        setVisible(true);
    }
    
    public boolean hasErrors() {
        return tabErros.getRowCount() > 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblErros = new javax.swing.JTable();

        setTitle("Erros/Alertas da última verificação");

        tblErros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Linha", "Coluna", "Mensagem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblErros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblErros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblErros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblErros;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel tabErros;
}
