/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.alg.gui;

import fatec.alg.Principal;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Caique Siqueira
 */
public class FrmSobre extends javax.swing.JFrame {

    private final static String URL_HOSPEDAGEM = "https://github.com/cslclaman/AlogInterpreter";
    private final static String URL_CONTATO_EMAIL = "interpretador-alog-fatecso@outlook.com.br";

    /**
     * Creates new form FrmSobre
     */
    public FrmSobre() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(
                getClass().getResource("/fatec/alg/gui/imagens/logo-interpr-64.png"))
                .getImage()
        );
        lblHospedagem.setText(lblHospedagem.getText().trim() + " " + URL_HOSPEDAGEM);
        txtEmail.setText(URL_CONTATO_EMAIL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFaculdadeCurso = new javax.swing.JLabel();
        lblLogoFaculdade = new javax.swing.JLabel();
        lblNomeProjeto = new javax.swing.JLabel();
        lblSobreProjeto = new javax.swing.JLabel();
        lblNomeOrientador = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        lblHospedagem = new javax.swing.JLabel();
        lblVersao = new javax.swing.JLabel();
        btnCopiarEmail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sobre o programa");

        lblFaculdadeCurso.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblFaculdadeCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFaculdadeCurso.setText("Fatec Sorocaba - Curso de Análise e Desenvolvimento de Sistemas");

        lblLogoFaculdade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/alg/gui/imagens/logo-fatecso-64.png"))); // NOI18N

        lblNomeProjeto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeProjeto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeProjeto.setText("Interpretador de Algoritmos");

        lblSobreProjeto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSobreProjeto.setText("Trabalho de Graduação do aluno Caíque de Souza Lima Siqueira");

        lblNomeOrientador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeOrientador.setText("Orientador: Prof. Dimas Ferreira Cardoso");

        jLabel6.setText("Contato: ");

        txtEmail.setEditable(false);
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblHospedagem.setForeground(new java.awt.Color(0, 0, 255));
        lblHospedagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospedagem.setText("Projeto hospedado em ");
        lblHospedagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHospedagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHospedagemMouseClicked(evt);
            }
        });

        lblVersao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblVersao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersao.setText(String.format("Versão %s (%s) - build %d", Principal.VERSAO_NUM, Principal.VERSAO_DATA, Principal.VERSAO_BUILD));

        btnCopiarEmail.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnCopiarEmail.setText("Copiar");
        btnCopiarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFaculdadeCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNomeProjeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVersao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHospedagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSobreProjeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNomeOrientador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogoFaculdade))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 8, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCopiarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFaculdadeCurso)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVersao)
                        .addGap(18, 18, 18)
                        .addComponent(lblSobreProjeto))
                    .addComponent(lblLogoFaculdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeOrientador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHospedagem)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCopiarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void lblHospedagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHospedagemMouseClicked
        try {
            Desktop.getDesktop().browse(new URI(URL_HOSPEDAGEM));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(this.getClass().getName()).log(
                    Level.WARNING, 
                    "{0} - {1}",
                    new Object[]{ex.getClass().getName(), ex.getMessage()});
        }
    }//GEN-LAST:event_lblHospedagemMouseClicked

    private void btnCopiarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarEmailActionPerformed
        StringSelection selection;
        Clipboard clipboard;
        selection = new StringSelection(URL_CONTATO_EMAIL);
        clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, selection);
    }//GEN-LAST:event_btnCopiarEmailActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopiarEmail;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblFaculdadeCurso;
    private javax.swing.JLabel lblHospedagem;
    private javax.swing.JLabel lblLogoFaculdade;
    private javax.swing.JLabel lblNomeOrientador;
    private javax.swing.JLabel lblNomeProjeto;
    private javax.swing.JLabel lblSobreProjeto;
    private javax.swing.JLabel lblVersao;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
